---
openapi: 3.0.0
info:
  title: Retail Banking - New account opening status for the customer
  version: 1.0.0
  description: API for determining the status of new accounts opened based on AccountID and reason for pending status # Important - Prompt semantically matched to description
paths:
  "/newBankAccountStatus":
    get:
      summary: Get a list of all open new accounts and thier status
      description: Get a list of all open new accounts and thier status
      operationId: getAllOpenAccountStatus
      parameters:
      - name : AccountID
        in: path
        description: The account ID of the customer looking for status
        required: true
        schema:
          type: int
      responses:
        '200':
          description: Successful response containing the account status details
          content:
            application/json:
              schema:
                type: object
                properties:
                  AccountName:
                    type: string
                    description: The name of the customer corresponding to AccountID
                  AccountID:
                    type: int
                    description: The account id of the customer  
                  Reason:
                    type: string
                    description: The reason for open status
                  Status:
                    type: string
                    description: The status of the accountid provided

